language: ruby
install:
  - curl -L https://www.opscode.com/chef/install.sh | sudo bash -s -- -P chefdk
before_script:
  - ./build.sh
script:
  - echo "No tests implemented (yet...)"
after_script:
  - ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL="b3ae55940f91"
    - GIT_NAME="Peter Halliday"
    - GIT_EMAIL="pghalliday@gmail.com"
    - DEPLOY_BRANCH="master"
