alias tmux-helios-application-framework="TERM=xterm-256color tmuxomatic ~/.dotfiles/tmuxomatic/helios-application-framework"
alias tmux-helios-development-infrastructure="TERM=xterm-256color tmuxomatic ~/.dotfiles/tmuxomatic/helios-development-infrastructure"
alias tmux-tasks="TERM=xterm-256color tmuxomatic ~/.dotfiles/tmuxomatic/tasks"
alias tmux-grunt-mocha-test="TERM=xterm-256color tmuxomatic ~/.dotfiles/tmuxomatic/grunt-mocha-test"
alias tmux-jira-project-analysis="TERM=xterm-256color tmuxomatic ~/.dotfiles/tmuxomatic/jira-project-analysis"
alias tmux-dotfiles="TERM=xterm-256color tmuxomatic ~/.dotfiles/tmuxomatic/dotfiles"
alias tmux-spikes="TERM=xterm-256color tmuxomatic ~/.dotfiles/tmuxomatic/spikes"
alias tmux-vim="TERM=xterm-256color tmuxomatic ~/.dotfiles/tmuxomatic/vim"
